function(lingmo_pch target)
    cmake_parse_arguments(PCH "" "" "PUBLIC;PRIVATE" ${ARGN})
    if(PCH_PRIVATE)
        target_precompile_headers(${target} PRIVATE ${PCH_PRIVATE})
    endif()
    if(PCH_PUBLIC)
        target_precompile_headers(${target} PUBLIC ${PCH_PUBLIC})
    endif()
endfunction()
