option(LINGMO_ENABLE_SANITIZERS "Enable address/undefined behavior sanitizers" OFF)

if(LINGMO_ENABLE_SANITIZERS AND NOT MSVC)
    include(CheckCXXCompilerFlag)
    check_cxx_compiler_flag(-fsanitize=address HAS_ASAN)
    if(HAS_ASAN)
        add_compile_options(-fsanitize=address -fno-omit-frame-pointer)
        add_link_options(-fsanitize=address)
    endif()
    check_cxx_compiler_flag(-fsanitize=undefined HAS_UBSAN)
    if(HAS_UBSAN)
        add_compile_options(-fsanitize=undefined)
        add_link_options(-fsanitize=undefined)
    endif()
endif()
